# Generated by Django 4.1.3 on 2022-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouriersCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('courier_name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
