# Generated by Django 4.1.3 on 2022-11-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_id', models.IntegerField()),
                ('awb', models.IntegerField(unique=True)),
                ('order_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('product_desc', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
    ]
